# Generated by Django 5.2.8 on 2025-12-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
