# Generated by Django 5.2.8 on 2025-12-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_author_alter_books_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
