# Generated by Django 5.2.9 on 2025-12-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
